// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/competitions": {
            "get": {
                "description": "Get all competitions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competitions"
                ],
                "summary": "Retrieve a list of all available competitions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.APICompetition"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APICompetition": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Unique identifier for the competition",
                    "type": "integer"
                },
                "name": {
                    "description": "Name of the competition (e.g., \"NRL\", \"NRLW\")",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Tipping API",
	Description:      "This is the API for the Tipping Application to interact with NRL data.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
