name: Test

on: [push, pull_request]

jobs:
  test-backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      # Run the tests
      - run: |
          echo "Running backend tests"
          cd backend
          go test -v ./tests/...
